#!/usr/bin/env python

import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], "../.."))

import dot_init

import click
import numpy
import PIL.Image
import rembg

@click.group()
def cli():
    pass


@click.command()
@click.option("--input-file", default=None, required=True, help="image file name")
@click.option("--output-file", default=None, required=True, help="output file name")
def bgrem(input_file: str, output_file: str):
    """
    Remove background from image.
    """

    input_image = PIL.Image.open(input_file)
    input_array = numpy.array(input_image)
    output_array = rembg.remove(input_array, bgcolor=(255, 255, 255, 255))
    output_image = PIL.Image.fromarray(output_array)
    output_image.save(output_file)

cli.add_command(bgrem)

if __name__ == "__main__":
    cli()